// Local message cache for offline reading

export interface CachedMessage {
  id: string;
  text: string;
  author_id: string;
  created_at: string;
  image_url: string | null;
  reply_to_id: string | null;
  profiles: { display_name: string | null; avatar_url: string | null } | null;
  reactions?: Array<{ reaction_type: string; user_id: string; id?: string }>;
  reply_to?: {
    id?: string;
    text: string;
    author_id?: string;
    profiles?: { display_name: string | null } | null;
    author?: { display_name: string | null } | null;
  } | null;
  // Allow extra properties for different chat types
  [key: string]: unknown;
}

interface CacheEntry {
  messages: CachedMessage[];
  timestamp: number;
}

const CACHE_KEY_PREFIX = "ignite_message_cache_";
const CACHE_EXPIRY_MS = 7 * 24 * 60 * 60 * 1000; // 7 days
const MAX_CACHED_MESSAGES = 100; // Per chat

// Known fake placeholder names that were generated by the old buggy code
// These names should be cleared from caches as they are NOT real user names
const FAKE_PLACEHOLDER_NAMES = new Set([
  "Alex Smith", "Alex Johnson", "Alex Brown", "Alex Davis", "Alex Wilson", "Alex Moore", "Alex Clark", "Alex Lewis", "Alex Walker", "Alex Hall",
  "Jordan Smith", "Jordan Johnson", "Jordan Brown", "Jordan Davis", "Jordan Wilson", "Jordan Moore", "Jordan Clark", "Jordan Lewis", "Jordan Walker", "Jordan Hall",
  "Taylor Smith", "Taylor Johnson", "Taylor Brown", "Taylor Davis", "Taylor Wilson", "Taylor Moore", "Taylor Clark", "Taylor Lewis", "Taylor Walker", "Taylor Hall",
  "Morgan Smith", "Morgan Johnson", "Morgan Brown", "Morgan Davis", "Morgan Wilson", "Morgan Moore", "Morgan Clark", "Morgan Lewis", "Morgan Walker", "Morgan Hall",
  "Casey Smith", "Casey Johnson", "Casey Brown", "Casey Davis", "Casey Wilson", "Casey Moore", "Casey Clark", "Casey Lewis", "Casey Walker", "Casey Hall",
  "Riley Smith", "Riley Johnson", "Riley Brown", "Riley Davis", "Riley Wilson", "Riley Moore", "Riley Clark", "Riley Lewis", "Riley Walker", "Riley Hall",
  "Quinn Smith", "Quinn Johnson", "Quinn Brown", "Quinn Davis", "Quinn Wilson", "Quinn Moore", "Quinn Clark", "Quinn Lewis", "Quinn Walker", "Quinn Hall",
  "Avery Smith", "Avery Johnson", "Avery Brown", "Avery Davis", "Avery Wilson", "Avery Moore", "Avery Clark", "Avery Lewis", "Avery Walker", "Avery Hall",
  "Parker Smith", "Parker Johnson", "Parker Brown", "Parker Davis", "Parker Wilson", "Parker Moore", "Parker Clark", "Parker Lewis", "Parker Walker", "Parker Hall",
  "Drew Smith", "Drew Johnson", "Drew Brown", "Drew Davis", "Drew Wilson", "Drew Moore", "Drew Clark", "Drew Lewis", "Drew Walker", "Drew Hall",
]);

// Check if a name is a fake placeholder
function isFakePlaceholderName(name: string | null | undefined): boolean {
  if (!name) return false;
  return FAKE_PLACEHOLDER_NAMES.has(name);
}

// Sanitize messages by clearing fake placeholder names (they will be re-fetched from DB)
function sanitizeMessages(messages: CachedMessage[]): CachedMessage[] {
  return messages.map(msg => {
    let needsUpdate = false;
    let profiles = msg.profiles;
    let reply_to = msg.reply_to;
    
    // Check main message profile
    if (profiles && isFakePlaceholderName(profiles.display_name)) {
      profiles = { ...profiles, display_name: null };
      needsUpdate = true;
    }
    
    // Check reply_to profile
    if (reply_to) {
      if (reply_to.profiles && isFakePlaceholderName(reply_to.profiles.display_name)) {
        reply_to = { ...reply_to, profiles: { ...reply_to.profiles, display_name: null } };
        needsUpdate = true;
      }
      if (reply_to.author && isFakePlaceholderName(reply_to.author.display_name)) {
        reply_to = { ...reply_to, author: { ...reply_to.author, display_name: null } };
        needsUpdate = true;
      }
    }
    
    if (needsUpdate) {
      return { ...msg, profiles, reply_to };
    }
    return msg;
  });
}

function getCacheKey(type: "team" | "club" | "group" | "broadcast" | "dm", targetId: string): string {
  return `${CACHE_KEY_PREFIX}${type}_${targetId}`;
}

// Get cached messages for a specific chat
export function getCachedMessages(type: "team" | "club" | "group" | "broadcast" | "dm", targetId: string): CachedMessage[] {
  try {
    // Check if localStorage is available (Safari private mode blocks it)
    if (typeof localStorage === 'undefined') return [];
    
    const key = getCacheKey(type, targetId);
    const stored = localStorage.getItem(key);
    if (!stored) return [];

    const entry: CacheEntry = JSON.parse(stored);
    
    // Check if cache is expired
    if (Date.now() - entry.timestamp > CACHE_EXPIRY_MS) {
      try {
        localStorage.removeItem(key);
      } catch {}
      return [];
    }

    // Sanitize messages to remove fake placeholder names
    const sanitized = sanitizeMessages(entry.messages);
    
    // If we sanitized any messages, update the cache
    const hasFakeNames = sanitized.some((msg, i) => msg !== entry.messages[i]);
    if (hasFakeNames) {
      console.log("[MessageCache] Cleared fake placeholder names from cache");
      cacheMessages(type, targetId, sanitized);
    }

    return sanitized;
  } catch {
    return [];
  }
}

// Save messages to cache
export function cacheMessages(
  type: "team" | "club" | "group" | "broadcast" | "dm",
  targetId: string,
  messages: CachedMessage[]
): void {
  try {
    // Check if localStorage is available (Safari private mode blocks it)
    if (typeof localStorage === 'undefined') return;
    
    const key = getCacheKey(type, targetId);
    
    // Only cache the most recent messages
    const messagesToCache = messages.slice(0, MAX_CACHED_MESSAGES);
    
    const entry: CacheEntry = {
      messages: messagesToCache,
      timestamp: Date.now(),
    };

    try {
      localStorage.setItem(key, JSON.stringify(entry));
    } catch (quotaError) {
      // localStorage might be full - try to clear old caches
      clearOldCaches();
      try {
        localStorage.setItem(key, JSON.stringify(entry));
      } catch {
        // Still failing - skip silently
      }
    }
  } catch {
    // Ignore errors - caching is not critical
  }
}

// Add a single message to cache (for optimistic updates)
export function addMessageToCache(
  type: "team" | "club" | "group" | "broadcast" | "dm",
  targetId: string,
  message: CachedMessage
): void {
  try {
    const existing = getCachedMessages(type, targetId);
    
    // Add to beginning (newest first)
    const updated = [message, ...existing.filter(m => m.id !== message.id)];
    
    cacheMessages(type, targetId, updated);
  } catch {
    console.error("Failed to add message to cache");
  }
}

// Remove a message from cache (for deletion)
export function removeMessageFromCache(
  type: "team" | "club" | "group" | "broadcast" | "dm",
  targetId: string,
  messageId: string
): void {
  try {
    const existing = getCachedMessages(type, targetId);
    const updated = existing.filter(m => m.id !== messageId);
    cacheMessages(type, targetId, updated);
  } catch {
    // Ignore errors - caching is not critical
  }
}

// Clear old caches to free up space
function clearOldCaches(): void {
  try {
    const keysToRemove: string[] = [];
    
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key?.startsWith(CACHE_KEY_PREFIX)) {
        try {
          const stored = localStorage.getItem(key);
          if (stored) {
            const entry: CacheEntry = JSON.parse(stored);
            if (Date.now() - entry.timestamp > CACHE_EXPIRY_MS) {
              keysToRemove.push(key);
            }
          }
        } catch {
          keysToRemove.push(key);
        }
      }
    }

    keysToRemove.forEach(key => localStorage.removeItem(key));
  } catch {
    // Ignore errors
  }
}

// Check if we have cached messages for a chat
export function hasCachedMessages(type: "team" | "club" | "group" | "broadcast" | "dm", targetId: string): boolean {
  return getCachedMessages(type, targetId).length > 0;
}

// Check if messages unexpectedly dropped to 0 (had cache but now empty)
// Returns true if a refetch should be triggered
export function shouldRefetchMessages(
  type: "team" | "club" | "group" | "broadcast" | "dm",
  targetId: string,
  fetchedCount: number
): boolean {
  if (fetchedCount > 0) return false;
  
  // If we fetched 0 messages but have cached messages, something is wrong
  const cachedCount = getCachedMessages(type, targetId).length;
  return cachedCount > 0;
}

// Clear cache for a specific chat
export function clearMessageCache(type: "team" | "club" | "group" | "broadcast" | "dm", targetId: string): void {
  try {
    const key = getCacheKey(type, targetId);
    localStorage.removeItem(key);
  } catch {
    // Ignore errors
  }
}
