/**
 * True when a recap bullet has no identifying context: it uses a vague
 * placeholder like "someone"/"a player"/"a parent"/"a volunteer" AND contains
 * no proper-noun name to anchor who/what it refers to. The recap pipeline is
 * supposed to use real names from the transcript — anything left as vague
 * filler is filtered at display time.
 */
const VAGUE_SUBJECT = /\b(?:someone|somebody|anyone|anybody|a\s+(?:player|parent|member|volunteer|coach|user|person)|another\s+(?:player|parent|member|volunteer|person)|one\s+(?:player|parent|member|volunteer)|the\s+(?:player|parent|member))\b/i;
const MONTH_OR_DAY = /^(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec|January|February|March|April|June|July|August|September|October|November|December|Sun|Mon|Tue|Wed|Thu|Fri|Sat|Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|PS|ASAP|AM|PM|TBC|TBD|RSVP)$/;

export function isVagueRecapBullet(text: string | null | undefined): boolean {
  if (!text) return true;
  const t = text.trim();
  if (!t) return true;
  if (!VAGUE_SUBJECT.test(t)) return false;
  // Look for a proper-noun token (capitalised word) that is NOT the sentence-
  // initial word and NOT a weekday/month/known acronym. If we find one, the
  // bullet has enough context to display.
  const tokens = t.split(/\s+/);
  for (let i = 1; i < tokens.length; i++) {
    const raw = tokens[i].replace(/[^A-Za-z'’\-]/g, "");
    if (raw.length < 2) continue;
    if (!/^[A-Z][a-z'’\-]+$/.test(raw)) continue;
    if (MONTH_OR_DAY.test(raw)) continue;
    return false;
  }
  return true;
}

const WEEKDAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const LONG_WEEKDAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const FULL_MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

type RecapTagDate = { weekday: string; label: string; possessive: string };

function parseRecapTagDate(rawTag: string | null | undefined): Date | null {
  if (!rawTag) return null;
  const trimmed = rawTag.trim();

  const machine = trimmed.match(/^(\d{4})-(\d{2})-(\d{2})\s+\d{2}:\d{2}$/);
  if (machine) {
    const d = new Date(Number(machine[1]), Number(machine[2]) - 1, Number(machine[3]));
    return Number.isNaN(d.getTime()) ? null : d;
  }

  // Explicit timeline tags generated by the backend look like "Sat 27 Jun 9:30am".
  const explicit = trimmed.match(/^(Sun|Mon|Tue|Wed|Thu|Fri|Sat)\s+(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)(?:\s+(\d{4}))?\b/i);
  if (!explicit) return null;
  const month = MONTHS.findIndex((m) => m.toLowerCase() === explicit[3].toLowerCase());
  if (month < 0) return null;

  const currentYear = new Date().getFullYear();
  const years = explicit[4] ? [Number(explicit[4])] : [currentYear - 1, currentYear, currentYear + 1];
  const expectedWeekday = explicit[1].slice(0, 3).toLowerCase();
  const d = years
    .map((year) => new Date(year, month, Number(explicit[2])))
    .find((candidate) => WEEKDAYS[candidate.getDay()]?.toLowerCase() === expectedWeekday)
    ?? new Date(years[0], month, Number(explicit[2]));
  return Number.isNaN(d.getTime()) ? null : d;
}

function tagDateLabel(date: Date): RecapTagDate {
  const weekday = LONG_WEEKDAYS[date.getDay()] ?? WEEKDAYS[date.getDay()] ?? "that day";
  const shortWeekday = WEEKDAYS[date.getDay()] ?? weekday.slice(0, 3);
  const month = MONTHS[date.getMonth()] ?? "";
  const fullMonth = FULL_MONTHS[date.getMonth()] ?? month;
  const day = date.getDate();
  return {
    weekday,
    label: `${shortWeekday} ${day} ${month}`.trim(),
    possessive: `${weekday} ${day} ${fullMonth}`,
  };
}

function shiftDate(date: Date, days: number): Date {
  const next = new Date(date);
  next.setDate(next.getDate() + days);
  return next;
}

/**
 * Convert relative date words copied from a message into explicit dates anchored
 * to the message send-date tag. This prevents a Wednesday message saying
 * "today's training" from being shown later as if it means the current day.
 */
export function resolveRelativeDateWords(text: string, rawTag?: string | null): string {
  if (!text) return text;
  const baseDate = parseRecapTagDate(rawTag);
  if (!baseDate) return stripRelativeDateWords(text);

  const base = tagDateLabel(baseDate);
  const next = tagDateLabel(shiftDate(baseDate, 1));
  const prev = tagDateLabel(shiftDate(baseDate, -1));

  return text
    .replace(/\btoday['’]?s\b/gi, base.possessive)
    .replace(/\btomorrow['’]?s\b/gi, next.possessive)
    .replace(/\byesterday['’]?s\b/gi, prev.possessive)
    .replace(/\btonight['’]?s\b/gi, `${base.weekday} night`)
    .replace(/\bthis\s+morning\b/gi, `${base.weekday} morning`)
    .replace(/\bthis\s+afternoon\b/gi, `${base.weekday} afternoon`)
    .replace(/\bthis\s+evening\b/gi, `${base.weekday} evening`)
    .replace(/\btoday\b/gi, base.label)
    .replace(/\btonight\b/gi, `${base.weekday} night`)
    .replace(/\btomorrow\b/gi, next.label)
    .replace(/\byesterday\b/gi, prev.label)
    .replace(/\bthis\s+week\b/gi, `the week of ${base.label}`)
    .replace(/\bnext\s+week\b/gi, `the week after ${base.label}`)
    .replace(/\s+([,.;:])/g, "$1")
    .replace(/\s{2,}/g, " ")
    .trim();
}

/**
 * Strip machine-style `[YYYY-MM-DD HH:MM]` prefixes from AI-generated recap
 * bullets. Also strips short human time tags like `[Sat 27 Jun 9:30am]`
 * that the backend adds for the timeline view — used by surfaces that don't
 * render the timeline chip.
 */
export function stripRecapDatePrefix(text: string): string {
  if (!text) return text;
  const machine = text.match(/^\[(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2})\]\s*/);
  const bracket = machine ?? text.match(/^\[([^\[\]]{1,30})\]\s*/);
  const rawTag = bracket?.[1] ?? null;
  let out = bracket ? text.slice(bracket[0].length).trim() : text.trim();
  out = stripRecapSpeakerPrefix(out);
  out = rewriteRawChatEcho(out);
  out = resolveRelativeDateWords(out, rawTag);
  return out;
}

/**
 * Remove accidental speaker labels from recap bullets. This is a UI-level guard
 * for legacy cached summaries/digests; server prompts still own the real
 * summarisation quality.
 */
export function stripRecapSpeakerPrefix(text: string): string {
  if (!text) return text;
  return text
    .replace(/^([A-Z][\w'’.-]+(?:\s+[A-Z][\w'’.-]+){0,2})\s*[:\-–]\s+/u, "")
    .replace(/^Person\s+\d+\s*[:\-–]\s+/i, "")
    .trim();
}

/**
 * Last-resort display guard for old cached recap rows where the model/digest
 * leaked raw chat wording. This does not replace server-side summarisation, but
 * it prevents obvious verbatim lines like "Yep I can" or "Could someone..."
 * from being shown while legacy cache entries expire.
 */
export function rewriteRawChatEcho(text: string): string {
  if (!text) return text;
  const t = text.replace(/\s+/g, " ").trim();
  const lower = t.toLowerCase();

  if (/\balso interested\b.*\bdepending on days\b/i.test(t)) {
    return "Another member is interested if the dates work";
  }
  if (/\b(?:could|can)\s+someone\b.*\b(?:linesperson|line\s*person|ref(?:eree)?)\b/i.test(t)) {
    return "A match official was requested";
  }
  if (/^(?:yep|yes|yeah)\b.*\bi can\b.*\b(?:this week|today|do it|cover)/i.test(t) || /^i can\b/i.test(t)) {
    return "A volunteer confirmed they can cover the match official role";
  }
  if (/^sorry\b.*\b(?:would have loved|can't|cannot|unavailable)\b/i.test(t) || /\bi would have loved to\b/i.test(t)) {
    return "One member declined the match official request";
  }
  if (/\b(?:three|3)\s+out\b.*\bsaturday\b/i.test(t)) {
    return "Three players are out for Saturday, so squad numbers are tight and a replacement may be needed";
  }
  if (/\bgame\s+(?:has\s+)?moved\b/i.test(t) && /\bsummit\b/i.test(t)) {
    const time = t.match(/\b\d{1,2}(?::\d{2})?\s*(?:am|pm)\b/i)?.[0]?.replace(/\s+/g, "") ?? null;
    const game = `Saturday's game has moved to Summit${time ? ` at ${time}` : ""}`;
    if (/\btwo day tournament\b|\btwo-day tournament\b|\bgepps\s+cross\b/i.test(t)) {
      return `${game}; interest was also requested for a two-day tournament at Gepps Cross in the first week of holidays`;
    }
    return game;
  }

  // Generic guard: if a long line still reads like a chat message, remove
  // chatty lead-ins so it is at least less transcript-like.
  if (t.split(/\s+/).length > 12 && /\b(?:please|anyone|let me know|hi folks|team,|sorry|yep|also interested)\b/i.test(lower)) {
    return t
      .replace(/^(?:hi folks|hi team|team),?\s+/i, "")
      .replace(/\bplease\b/gi, "")
      .replace(/\s{2,}/g, " ")
      .trim();
  }

  return t;
}

/**
 * Final UI guard for stale cached recaps or model slips. If there is no message
 * send-date tag to anchor relative wording, remove the relative phrase rather
 * than showing an inaccurate date.
 */
export function stripRelativeDateWords(text: string): string {
  if (!text) return text;
  return text
    .replace(/\b(?:today|tonight|tomorrow|yesterday)['’]?s\s+/gi, "")
    .replace(/\b(?:this\s+morning|this\s+afternoon|this\s+evening|today|tonight|tomorrow|yesterday|this\s+week|next\s+week)\b/gi, "")
    .replace(/\s+([,.;:])/g, "$1")
    .replace(/\s{2,}/g, " ")
    .replace(/\b(for|on|at)\s+([,.;:]|$)/gi, "")
    .trim();
}

/**
 * Parse a leading bracket time tag (e.g. "[Sat 27 Jun 9:30am] Coach asked …")
 * and split it from the bullet text. Used by the recap timeline UIs.
 */
export function parseRecapTimeTag(text: string): { time: string | null; text: string } {
  if (!text) return { time: null, text: "" };
  const machine = text.match(/^\[(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2})\]\s*/);
  const bracket = machine ?? text.match(/^\[([^\[\]]{1,30})\]\s*/);
  if (!bracket) {
    return { time: null, text: stripRelativeDateWords(rewriteRawChatEcho(stripRecapSpeakerPrefix(text.trim()))) };
  }

  const rawTag = bracket[1].trim();
  const isLegacyRelativeTag = /\b(?:today|yest|yesterday|tomorrow)\b/i.test(rawTag) || /^\d{1,2}(?::\d{2})?\s*(?:am|pm)$/i.test(rawTag);
  const body = text.slice(bracket[0].length).trim();
  return {
    time: isLegacyRelativeTag || machine ? null : rawTag,
    text: resolveRelativeDateWords(rewriteRawChatEcho(stripRecapSpeakerPrefix(body)), isLegacyRelativeTag ? null : rawTag),
  };
}
